# Generated by Django 3.2.8 on 2021-10-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComunidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(choices=[('Caribe', 'Caribe'), ('Andina', 'Andina'), ('Pacifico', 'Pacifico'), ('Orinoquia', 'Orinoquia'), ('Amazonia', 'Amazonia'), ('Insular', 'Insular')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_prod', models.CharField(choices=[('tejido', 'tejido'), ('ceramica', 'ceramica'), ('joyeria', 'joyeria'), ('Orfebreria', 'Orfebreria'), ('tallado', 'tallado')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('caracteristica', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='authAppComInd.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Produc_comun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produc_comun', to='authAppComInd.comunidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produc_comun', to='authAppComInd.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidad', to='authAppComInd.region'),
        ),
    ]
